/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as PromptLibraryRouteImport } from './routes/prompt-library'
import { Route as SkillsLibraryRouteImport } from './routes/skills-library'
import { Route as SubstackRouteImport } from './routes/substack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptLibraryRoute = PromptLibraryRouteImport.update({
  id: '/prompt-library',
  path: '/prompt-library',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsLibraryRoute = SkillsLibraryRouteImport.update({
  id: '/skills-library',
  path: '/skills-library',
  getParentRoute: () => rootRouteImport,
} as any)
const SubstackRoute = SubstackRouteImport.update({
  id: '/substack',
  path: '/substack',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/playbooks': typeof PlaybooksRoute
  '/prompt-library': typeof PromptLibraryRoute
  '/skills-library': typeof SkillsLibraryRoute
  '/substack': typeof SubstackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/playbooks': typeof PlaybooksRoute
  '/prompt-library': typeof PromptLibraryRoute
  '/skills-library': typeof SkillsLibraryRoute
  '/substack': typeof SubstackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/playbooks': typeof PlaybooksRoute
  '/prompt-library': typeof PromptLibraryRoute
  '/skills-library': typeof SkillsLibraryRoute
  '/substack': typeof SubstackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/playbooks'
    | '/prompt-library'
    | '/skills-library'
    | '/substack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/playbooks'
    | '/prompt-library'
    | '/skills-library'
    | '/substack'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/playbooks'
    | '/prompt-library'
    | '/skills-library'
    | '/substack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  PlaybooksRoute: typeof PlaybooksRoute
  PromptLibraryRoute: typeof PromptLibraryRoute
  SkillsLibraryRoute: typeof SkillsLibraryRoute
  SubstackRoute: typeof SubstackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-library': {
      id: '/prompt-library'
      path: '/prompt-library'
      fullPath: '/prompt-library'
      preLoaderRoute: typeof PromptLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills-library': {
      id: '/skills-library'
      path: '/skills-library'
      fullPath: '/skills-library'
      preLoaderRoute: typeof SkillsLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/substack': {
      id: '/substack'
      path: '/substack'
      fullPath: '/substack'
      preLoaderRoute: typeof SubstackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  PlaybooksRoute: PlaybooksRoute,
  PromptLibraryRoute: PromptLibraryRoute,
  SkillsLibraryRoute: SkillsLibraryRoute,
  SubstackRoute: SubstackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
